#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor HDMI-0 -d     
#bspc monitor DP-2 -d    
bspc monitor  eDP1 -d    


bspc config border_width         2
bspc config window_gap		 14          

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## ----- Add your stuff from here ------ ##
pkill sxhkd
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

$HOME/.screenlayout/display.sh
pkill picom
#picom --config $HOME/.config/picom/picom.conf -b

pkill polybar
$HOME/.config/polybar/launch.sh &

nitrogen --restore &

xsetroot -cursor_name left_ptr

compton &
